site_name: mkdocs-bpmn-js

theme:
  name: mkdocs
  user_color_mode_toggle: true
  # custom_dir: theme

extra_css:
  - style.css

plugins:
  - bpmn-js:
      # render: image
      # image_command: ./node_modules/.bin/bpmn-to-image --no-title --no-footer $input:$output
